import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer/Footer";
import { AuthContextProvider } from "@/context/AuthContext";
import { getSession } from "@/authThing/action";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession();
  if (session.phone) {
    const phone = session.phone;
    console.log(phone);
  }

  return (
    <html lang="en">
      <AuthContextProvider>
        <body className={inter.className}>
          <div className="hidden md:block">
            <Header />
          </div>
          <div className="block md:hidden">
            <Navbar />
          </div>
          {children}
          <div>{session.phone !== "1234567890" && <Footer />}</div>
        </body>
      </AuthContextProvider>
    </html>
  );
}
